CaseTracker/Models/Case.cs
using System.ComponentModel.DataAnnotations;

namespace CaseTracker.Models
{
    public class Case
    {
        [Key]
        public int Id { get; set; }
        public int? ActivityId { get; set; } //assigned by employee
        public DateTime CreatedDateTime { get; set; } = DateTime.Now;
        public string CaseStatus { get; set; } = "Action Required";
        [Required]
        public string VslName { get; set; }
        public int VslOffNum { get; set; }    
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string ContactNum { get; set; }
        public string UserEmail { get; set; }


    }
}

CaseTracker/Models/ErrorViewModel.cs
namespace CaseTracker.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CaseTracker/Controllers/CasesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CaseTracker.Data;
using CaseTracker.Models;

namespace CaseTracker.Controllers
{
    public class CasesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CasesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Cases
        public async Task<IActionResult> Index()
        {
            IEnumerable<Case> objCaseList = _context.Case; //added from tutorial
            return View(await _context.Case.ToListAsync());
        }

        // GET: Cases/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @case = await _context.Case
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@case == null)
            {
                return NotFound();
            }

            return View(@case);
        }

        // GET: Cases/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cases/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CaseStatus,VslName,VslOffNum,ActivityId,UserFirstName,UserLastName,ContactNum,UserEmail")] Case @case)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@case);
                await _context.SaveChangesAsync();
                TempData["success"] = "Case created successfully";
                return RedirectToAction(nameof(Index));
            }
            return View(@case);
        }

        //Create a case (user side)
        public IActionResult userCreate()
        {
            return View();
        }

        // POST: Cases/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> userCreate([Bind("VslName,VslOffNum,UserFirstName,UserLastName,ContactNum,UserEmail")] Case @case)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@case);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(@case);
        }

        // GET: Cases/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @case = await _context.Case.FindAsync(id);
            if (@case == null)
            {
                return NotFound();
            }
            return View(@case);
        }

        // POST: Cases/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CaseStatus,VslName,VslOffNum,ActivityId,UserFirstName,UserLastName,ContactNum,UserEmail")] Case @case)
        {
            if (id != @case.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@case);
                    _context.SaveChanges();
                    TempData["success"] = "Case updated successfully";
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CaseExists(@case.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@case);
        }

        // GET: Cases/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @case = await _context.Case
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@case == null)
            {
                return NotFound();
            }

            return View(@case);
        }

        // POST: Cases/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @case = await _context.Case.FindAsync(id);
            _context.Case.Remove(@case);
            await _context.SaveChangesAsync();
            TempData["success"] = "Case deleted successfully";
            return RedirectToAction(nameof(Index));
        }

        private bool CaseExists(int id)
        {
            return _context.Case.Any(e => e.Id == id);
        }
    }
}

CaseTracker/Controllers/HomeController.cs
using CaseTracker.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CaseTracker.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CaseTracker/Views/Cases/Create.cshtml
@model CaseTracker.Models.Case

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Case</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CaseStatus" class="control-label"></label>
                <input asp-for="CaseStatus" class="form-control" />
                <span asp-validation-for="CaseStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VslName" class="control-label"></label>
                <input asp-for="VslName" class="form-control" />
                <span asp-validation-for="VslName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VslOffNum" class="control-label"></label>
                <input asp-for="VslOffNum" class="form-control" />
                <span asp-validation-for="VslOffNum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ActivityId" class="control-label"></label>
                <input asp-for="ActivityId" class="form-control" />
                <span asp-validation-for="ActivityId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserFirstName" class="control-label"></label>
                <input asp-for="UserFirstName" class="form-control" />
                <span asp-validation-for="UserFirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserLastName" class="control-label"></label>
                <input asp-for="UserLastName" class="form-control" />
                <span asp-validation-for="UserLastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactNum" class="control-label"></label>
                <input asp-for="ContactNum" class="form-control" />
                <span asp-validation-for="ContactNum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserEmail" class="control-label"></label>
                <input asp-for="UserEmail" class="form-control" />
                <span asp-validation-for="UserEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CaseTracker/Views/Cases/Delete.cshtml
@model CaseTracker.Models.Case

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Case</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CaseStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CaseStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VslName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VslName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VslOffNum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VslOffNum)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ActivityId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ActivityId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserFirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserFirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserLastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserLastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactNum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactNum)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserEmail)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CaseTracker/Views/Cases/Details.cshtml
@model CaseTracker.Models.Case

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Case</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ActivityId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ActivityId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CaseStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CaseStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VslName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VslName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VslOffNum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VslOffNum)
        </dd>
        
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserFirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserFirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserLastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserLastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactNum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactNum)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserEmail)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CaseTracker/Views/Cases/Edit.cshtml
@model CaseTracker.Models.Case

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Case</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CaseStatus" class="control-label"></label>
                <input asp-for="CaseStatus" class="form-control" />
                <span asp-validation-for="CaseStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VslName" class="control-label"></label>
                <input asp-for="VslName" class="form-control" />
                <span asp-validation-for="VslName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VslOffNum" class="control-label"></label>
                <input asp-for="VslOffNum" class="form-control" />
                <span asp-validation-for="VslOffNum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ActivityId" class="control-label"></label>
                <input asp-for="ActivityId" class="form-control" />
                <span asp-validation-for="ActivityId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserFirstName" class="control-label"></label>
                <input asp-for="UserFirstName" class="form-control" />
                <span asp-validation-for="UserFirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserLastName" class="control-label"></label>
                <input asp-for="UserLastName" class="form-control" />
                <span asp-validation-for="UserLastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactNum" class="control-label"></label>
                <input asp-for="ContactNum" class="form-control" />
                <span asp-validation-for="ContactNum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserEmail" class="control-label"></label>
                <input asp-for="UserEmail" class="form-control" />
                <span asp-validation-for="UserEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CaseTracker/Views/Cases/Index.cshtml
@model IEnumerable<CaseTracker.Models.Case>

@{
    ViewData["Title"] = "Index";
}



<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Case Tracker</h2>
        </div>
        <div class="col-6 text-end" id="addBtn">
            <a asp-controller="Cases" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-square"></i> &nbsp; New Case</a>
        </div> 
    </div>
    <br />


<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">
                @Html.DisplayNameFor(model => model.CaseStatus)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.ActivityId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VslName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VslOffNum)
            </th>            
            <th>
                @Html.DisplayNameFor(model => model.UserFirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserLastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ContactNum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserEmail)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr class="table-primary">
            <td>
                @Html.DisplayFor(modelItem => item.CaseStatus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ActivityId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VslName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VslOffNum)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.UserFirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserLastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContactNum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserEmail)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Update</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</div>

CaseTracker/Views/Cases/userCreate.cshtml
@model CaseTracker.Models.Case

@{
    ViewData["Title"] = "userCreate";
}

<h1>Case Submission Form</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="userCreate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
@*            <div class="form-group">
                <label asp-for="ActivityId" class="control-label"></label>
                <input asp-for="ActivityId" class="form-control" />
                <span asp-validation-for="ActivityId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDateTime" class="control-label"></label>
                <input asp-for="CreatedDateTime" class="form-control" />
                <span asp-validation-for="CreatedDateTime" class="text-danger"></span>
            </div>*@
@*            <div class="form-group">
                <label asp-for="CaseStatus" class="control-label"></label>
                <input asp-for="CaseStatus" class="form-control" />
                <span asp-validation-for="CaseStatus" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="VslName" class="control-label">Vessel Name</label>
                <input asp-for="VslName" class="form-control" />
                <span asp-validation-for="VslName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VslOffNum" class="control-label">Official Number</label>
                <input asp-for="VslOffNum" class="form-control" />
                <span asp-validation-for="VslOffNum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserFirstName" class="control-label">First Name</label>
                <input asp-for="UserFirstName" class="form-control" />
                <span asp-validation-for="UserFirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserLastName" class="control-label">Last Name</label>
                <input asp-for="UserLastName" class="form-control" />
                <span asp-validation-for="UserLastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactNum" class="control-label">Contact Phone Number</label>
                <input asp-for="ContactNum" class="form-control" />
                <span asp-validation-for="ContactNum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserEmail" class="control-label">Contact Email</label>
                <input asp-for="UserEmail" class="form-control" />
                <span asp-validation-for="UserEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CaseTracker/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to the Case Tracker</h1>
    <h4>Please select from an option below:</h4>
</div>

CaseTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CaseTracker</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/BootswatchTheme.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css"/>
    <link rel="stylesheet" href-"//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    @*<link rel="stylesheet" href="~/CaseTracker.styles.css" asp-append-version="true" />*@

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Case Tracker</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index">Home
            <span class="visually-hidden">(current)</span>
          </a>
        </li>
        <li class="nav-item">
           <a class="nav-link text-dark" asp-area="" asp-controller="Cases" asp-action="Index">Cases</a>
        </li>
        <li class="nav-item">
           <a class="nav-link text-dark" asp-area="" asp-controller="Cases" asp-action="userCreate">New Case</a>
        </li>
      </ul>
      <partial name="_LoginPartial" />
    </div>
  </div>
</nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="footer bg-dark">
        <div class="container">
            &copy; 2022 - CaseTracker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CaseTracker/Views/Shared/_notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}

@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["error"]');
    </script>
}